### ISSUE TITLE
GLib.Error: gst_parse_error: no element "nvstreammux" (1)

### ISSUE THREAD

**Issue by swo026** [pbridger/deepstream-video-pipeline#1]
Hello, I pulled the dockerfile you provided, but encountered GLib.Error when running `ds_pipeline.py` 

```
root@c4762d0ad73c:/home/deepstream_video_pipeline# python3 ds_pipeline.py
nvstreammux name=mux0 gpu-id=0 enable-padding=1 width=300 height=300 batch-size=8 batched-push-timeout=1000000 ! 
nvinfer config-file-path=detector_default.config gpu-id=0 batch-size=8 ! fakesink enable-last-sample=0
filesrc location=media/in.mp4 num-buffers=512 ! qtdemux ! h264parse ! nvv4l2decoder gpu-id=0 ! mux0.sink_0 
filesrc location=media/in.mp4 num-buffers=512 ! qtdemux ! h264parse ! nvv4l2decoder gpu-id=0 ! mux0.sink_1 
filesrc location=media/in.mp4 num-buffers=512 ! qtdemux ! h264parse ! nvv4l2decoder gpu-id=0 ! mux0.sink_2 
filesrc location=media/in.mp4 num-buffers=512 ! qtdemux ! h264parse ! nvv4l2decoder gpu-id=0 ! mux0.sink_3 

Traceback (most recent call last):
  File "ds_pipeline.py", line 31, in <module>
    pipeline = Gst.parse_launch(pipeline_cmd)
GLib.Error: gst_parse_error: no element "nvstreammux" (1)
```
I also tried to run it in the miniconda environment,  but another error occurred
```
(base) root@c4762d0ad73c:/home/deepstream_video_pipeline# python3 ds_pipeline.py 
Traceback (most recent call last):
  File "ds_pipeline.py", line 4, in <module>
    gi.require_version('Gst', '1.0')
  File "/opt/conda/lib/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available
```
Any idea about how to solve this? Many thanks.

**Comment by pbridger** [comment]
Try running python instead of python3?

**Comment by swo026** [comment]
@pbridger when running python instead of python3 I got SyntaxError
```
root@c4762d0ad73c:/home/deepstream_video_pipeline# python da_pipeline.py
python: can't open file 'da_pipeline.py': [Errno 2] No such file or directory
root@c4762d0ad73c:/home/deepstream_video_pipeline# python ds_pipeline.py 
  File "ds_pipeline.py", line 21
    '''
      ^
SyntaxError: invalid syntax

``` 
and 
```
(base) root@c4762d0ad73c:/home/deepstream_video_pipeline# python ds_pipeline.py 
Traceback (most recent call last):
  File "ds_pipeline.py", line 4, in <module>
    gi.require_version('Gst', '1.0')
  File "/opt/conda/lib/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available

```

**Comment by pbridger** [comment]
That implies an unexpected python version, which sounds like a broken container.

How are you starting it?
