### ISSUE TITLE
Traceback (most recent call last):   File "export_trt_engine.py", line 57, in <module>

### ISSUE THREAD

**Issue by locpv98** [pbridger/deepstream-video-pipeline#3]
root@3c52020d6f01:/app# python export_trt_engine.py --ssd-module-name ds_ssd300_4 --trt-module-name ds_trt_4

Using cache found in /root/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub
/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448234945/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
&&&& RUNNING TensorRT.trtexec [TensorRT v8001] # trtexec --onnx=checkpoints/ds_trt_4.onnx --saveEngine=checkpoints/ds_trt_4.engine --fp16 --explicitBatch --minShapes=image_nchw:1x3x300x300 --optShapes=image_nchw:8x3x300x300 --maxShapes=image_nchw:8x3x300x300 --buildOnly
[07/14/2021-07:20:26] [I] === Model Options ===
[07/14/2021-07:20:26] [I] Format: ONNX
[07/14/2021-07:20:26] [I] Model: checkpoints/ds_trt_4.onnx
[07/14/2021-07:20:26] [I] Output:
[07/14/2021-07:20:26] [I] === Build Options ===
[07/14/2021-07:20:26] [I] Max batch: explicit
[07/14/2021-07:20:26] [I] Workspace: 16 MiB
[07/14/2021-07:20:26] [I] minTiming: 1
[07/14/2021-07:20:26] [I] avgTiming: 8
[07/14/2021-07:20:26] [I] Precision: FP32+FP16
[07/14/2021-07:20:26] [I] Calibration: 
[07/14/2021-07:20:26] [I] Refit: Disabled
[07/14/2021-07:20:26] [I] Sparsity: Disabled
[07/14/2021-07:20:26] [I] Safe mode: Disabled
[07/14/2021-07:20:26] [I] Save engine: checkpoints/ds_trt_4.engine
[07/14/2021-07:20:26] [I] Load engine: 
[07/14/2021-07:20:26] [I] NVTX verbosity: 0
[07/14/2021-07:20:26] [I] Tactic sources: Using default tactic sources
[07/14/2021-07:20:26] [I] timingCacheMode: local
[07/14/2021-07:20:26] [I] timingCacheFile: 
[07/14/2021-07:20:26] [I] Input(s)s format: fp32:CHW
[07/14/2021-07:20:26] [I] Output(s)s format: fp32:CHW
[07/14/2021-07:20:26] [I] Input build shape: image_nchw=1x3x300x300+8x3x300x300+8x3x300x300
[07/14/2021-07:20:26] [I] Input calibration shapes: model
[07/14/2021-07:20:26] [I] === System Options ===
[07/14/2021-07:20:26] [I] Device: 0
[07/14/2021-07:20:26] [I] DLACore: 
[07/14/2021-07:20:26] [I] Plugins:
[07/14/2021-07:20:26] [I] === Inference Options ===
[07/14/2021-07:20:26] [I] Batch: Explicit
[07/14/2021-07:20:26] [I] Input inference shape: image_nchw=8x3x300x300
[07/14/2021-07:20:26] [I] Iterations: 10
[07/14/2021-07:20:26] [I] Duration: 3s (+ 200ms warm up)
[07/14/2021-07:20:26] [I] Sleep time: 0ms
[07/14/2021-07:20:26] [I] Streams: 1
[07/14/2021-07:20:26] [I] ExposeDMA: Disabled
[07/14/2021-07:20:26] [I] Data transfers: Enabled
[07/14/2021-07:20:26] [I] Spin-wait: Disabled
[07/14/2021-07:20:26] [I] Multithreading: Disabled
[07/14/2021-07:20:26] [I] CUDA Graph: Disabled
[07/14/2021-07:20:26] [I] Separate profiling: Disabled
[07/14/2021-07:20:26] [I] Time Deserialize: Disabled
[07/14/2021-07:20:26] [I] Time Refit: Disabled
[07/14/2021-07:20:26] [I] Skip inference: Enabled
[07/14/2021-07:20:26] [I] Inputs:
[07/14/2021-07:20:26] [I] === Reporting Options ===
[07/14/2021-07:20:26] [I] Verbose: Disabled
[07/14/2021-07:20:26] [I] Averages: 10 inferences
[07/14/2021-07:20:26] [I] Percentile: 99
[07/14/2021-07:20:26] [I] Dump refittable layers:Disabled
[07/14/2021-07:20:26] [I] Dump output: Disabled
[07/14/2021-07:20:26] [I] Profile: Disabled
[07/14/2021-07:20:26] [I] Export timing to JSON file: 
[07/14/2021-07:20:26] [I] Export output to JSON file: 
[07/14/2021-07:20:26] [I] Export profile to JSON file: 
[07/14/2021-07:20:26] [I] 
[07/14/2021-07:20:26] [I] === Device Information ===
[07/14/2021-07:20:26] [I] Selected Device: GeForce RTX 2060
[07/14/2021-07:20:26] [I] Compute Capability: 7.5
[07/14/2021-07:20:26] [I] SMs: 30
[07/14/2021-07:20:26] [I] Compute Clock Rate: 1.755 GHz
[07/14/2021-07:20:26] [I] Device Global Memory: 5931 MiB
[07/14/2021-07:20:26] [I] Shared Memory per SM: 64 KiB
[07/14/2021-07:20:26] [I] Memory Bus Width: 192 bits (ECC disabled)
[07/14/2021-07:20:26] [I] Memory Clock Rate: 7.001 GHz
[07/14/2021-07:20:26] [I] 
[07/14/2021-07:20:26] [I] TensorRT version: 7103
Traceback (most recent call last):
  File "export_trt_engine.py", line 57, in <module>
    trt_output = subprocess.run([
  File "/opt/conda/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['trtexec', '--onnx=checkpoints/ds_trt_4.onnx', '--saveEngine=checkpoints/ds_trt_4.engine', '--fp16', '--explicitBatch', '--minShapes=image_nchw:1x3x300x300', '--optShapes=image_nchw:8x3x300x300', '--maxShapes=image_nchw:8x3x300x300', '--buildOnly']' died with <Signals.SIGSEGV: 11>.

**Comment by locpv98** [comment]
hi Pbridger!!! I clone this project and run "make", then I run "make run-container" to start container. and i run "python export_tsc.py --ssd-module-name ds_ssd300_4 --trt-module-name ds_trt_4 --tsc-module-name ds_tsc_4" it worded, but when i try run "python export_trt_engine.py --ssd-module-name ds_ssd300_4 --trt-module-name ds_trt_4" it not word, like code in above??? Can you help me???
